TO.DO

  . bugs
  	- eleitos
  		erro do RUBENS OTONI GOMIDE (GO) - tem 7077 no sistema e tem 7139 no TSE

    - comites financeiros
      avaliar se os cnpjs que nao foram encontrados realmente nao fizemra doacao pra deputado federal


	. plano
		- separar as doações por tipo
      - verificar o de partido e doador
      - reprocessar as somas de partido e doadores

  . backlog
    - terminar de calcular os rankings de candidato
    - modelar estado




